import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { describe, it } from 'node:test'

const source = readFileSync(new URL('../src/renderer/components/SettingsDialog.vue', import.meta.url), 'utf8')
const mainEditorSource = readFileSync(new URL('../src/renderer/views/MainEditor.vue', import.meta.url), 'utf8')
const titleBarSource = readFileSync(new URL('../src/renderer/components/TitleBar.vue', import.meta.url), 'utf8')
const zhLocaleSource = readFileSync(new URL('../src/renderer/locales/zh-CN.json', import.meta.url), 'utf8')
const enLocaleSource = readFileSync(new URL('../src/renderer/locales/en-US.json', import.meta.url), 'utf8')
const aiSettingsViewSource = readFileSync(new URL('../src/renderer/utils/aiSettingsView.js', import.meta.url), 'utf8')
const aiSettingsSchemaSource = readFileSync(new URL('../electron/aiSettingsSchema.js', import.meta.url), 'utf8')

describe('settings dialog Codex-style layout', () => {
  it('uses an app-level settings workbench shell instead of the generic modal container', () => {
    assert.doesNotMatch(source, /<ModalDialog[\s\S]*:show="show"[\s\S]*:title="t\('settings\.title'\)/)
    assert.match(source, /class="settings-page-shell"/)
    assert.match(source, /class="settings-return-button"/)
    assert.match(source, /class="settings-content-panel"/)
  })

  it('reuses the full app title bar inside the settings page', () => {
    assert.match(source, /class="settings-window-titlebar"/)
    assert.match(source, /<TitleBar\b/)
    assert.match(source, /import TitleBar from '\.\/TitleBar\.vue'/)
    assert.match(source, /@open-settings="handleTitleBarOpenSettings"/)
    assert.match(source, /@menu-action="handleTitleBarMenuAction"/)
    assert.match(source, /:show-layout-controls="false"/)
    assert.match(titleBarSource, /showLayoutControls:\s*{[\s\S]*type:\s*Boolean,[\s\S]*default:\s*true[\s\S]*}/)
    assert.match(titleBarSource, /<div v-if="showLayoutControls" class="layout-controls"/)
    assert.match(source, /grid-template-rows:\s*var\(--titlebar-height\)\s+minmax\(0,\s*1fr\);/)
  })

  it('wires title bar state and menu actions through the main editor', () => {
    assert.match(mainEditorSource, /:left-sidebar-collapsed="isSidebarCollapsed"/)
    assert.match(mainEditorSource, /:right-sidebar-collapsed="isRightSidebarCollapsed"/)
    assert.match(mainEditorSource, /@menu-action="handleTitleBarMenuAction"/)
  })

  it('mounts heavy async dialogs only when they are opened', () => {
    assert.match(mainEditorSource, /<SettingsDialog\s+v-if="showSettingsDialog"/)
    assert.match(mainEditorSource, /<AboutDialog\s+v-if="showAboutDialog"/)
    assert.match(mainEditorSource, /<GlobalSearchDialog\s+v-if="showGlobalSearchDialog"/)
    assert.match(mainEditorSource, /const SettingsDialog = defineAsyncComponent\(\(\) => import\('\.\.\/components\/SettingsDialog\.vue'\)\)/)
    assert.match(mainEditorSource, /const AboutDialog = defineAsyncComponent\(\(\) => import\('\.\.\/components\/AboutDialog\.vue'\)\)/)
    assert.match(mainEditorSource, /const GlobalSearchDialog = defineAsyncComponent\(\(\) => import\('\.\.\/components\/GlobalSearchDialog\.vue'\)\)/)
  })

  it('uses the spacious sidebar rhythm from the approved design', () => {
    assert.match(source, /grid-template-columns:\s*324px\s+minmax\(0,\s*1fr\);/)
    assert.match(source, /\.settings-page-sidebar\s*{[\s\S]*padding:\s*14px 16px 18px 18px;/)
    assert.match(source, /\.settings-return-button\s*{[\s\S]*height:\s*34px;[\s\S]*padding:\s*0 12px;[\s\S]*border-radius:\s*8px;/)
    assert.match(source, /\.settings-search-input\s*{[\s\S]*height:\s*36px;[\s\S]*padding:\s*0 12px 0 34px;[\s\S]*border-radius:\s*9px;/)
    assert.match(source, /\.settings-nav-item\s*{[\s\S]*min-height:\s*34px;[\s\S]*border-radius:\s*8px;/)
    assert.match(source, /\.settings-nav-list\s*{[\s\S]*gap:\s*3px;/)
    assert.doesNotMatch(source, /settings-nav-item-dot/)
  })

  it('places settings search in the left sidebar between return and navigation', () => {
    const sidebarStart = source.indexOf('<aside class="settings-page-sidebar settings-nav">')
    const returnButton = source.indexOf('class="settings-return-button"', sidebarStart)
    const searchWrap = source.indexOf('class="settings-search-wrap"', sidebarStart)
    const navLabel = source.indexOf('class="settings-nav-label"', sidebarStart)
    const navList = source.indexOf('class="settings-nav-list"', sidebarStart)
    const toolbarStart = source.indexOf('<header class="settings-toolbar">')
    const toolbarEnd = source.indexOf('</header>', toolbarStart)
    const toolbarMarkup = source.slice(toolbarStart, toolbarEnd)

    assert.ok(sidebarStart >= 0)
    assert.ok(returnButton > sidebarStart)
    assert.ok(searchWrap > returnButton)
    assert.ok(navLabel > searchWrap)
    assert.ok(navList > navLabel)
    assert.doesNotMatch(toolbarMarkup, /settings-search-wrap/)
  })

  it('gives the live appearance preview enough room to read as a real panel', () => {
    assert.match(source, /\.settings-row--preview\s*{[\s\S]*grid-template-columns:\s*minmax\(128px,\s*1fr\)\s+minmax\(420px,\s*520px\);[\s\S]*min-height:\s*190px;/)
    assert.match(source, /\.live-preview\s*{[\s\S]*width:\s*100%;[\s\S]*min-height:\s*170px;/)
    assert.match(source, /\.live-preview-toolbar\s*{[\s\S]*height:\s*30px;/)
    assert.match(source, /\.live-preview-content\s*{[\s\S]*padding:\s*16px 18px;[\s\S]*gap:\s*8px;/)
  })

  it('keeps font size value out of the row title because the input already shows it', () => {
    assert.doesNotMatch(source, /title:\s*t\('settings\.fontSize',\s*\{\s*size:/)
    assert.match(source, /title:\s*t\('settings\.fontSize'\)/)
    assert.match(zhLocaleSource, /"fontSize":\s*"字体大小"/)
    assert.match(enLocaleSource, /"fontSize":\s*"Font Size"/)
  })

  it('keeps provider cards compact with only delete actions on the right edge', () => {
    assert.doesNotMatch(source, /class="ai-api-meta"/)
    assert.doesNotMatch(source, /class="ai-api-status"/)
    assert.doesNotMatch(source, /class="ai-api-actions"/)
    assert.doesNotMatch(source, /M21 12a9 9 0 1 1-2\.64-6\.36/)
    assert.match(source, /class="ai-api-card-actions"/)
    assert.match(source, /class="ai-api-card-action ai-api-card-action--danger"/)
    assert.match(source, /class="ai-provider-brand-mark ai-provider-brand-mark--card"/)
    assert.match(source, /resolveAiProviderIcon\(provider\)\.path/)
    assert.match(source, /<span class="ai-api-copy">\s*<span class="ai-api-title">\s*<span>{{ provider\.name \|\| t\('settings\.aiProviderUnnamed'\) }}<\/span>\s*<span v-if="!provider\.hasApiKey" class="ai-api-badge ai-api-badge--warn">{{ t\('settings\.aiMissingKey'\) }}<\/span>\s*<\/span>\s*<\/span>\s*<span class="ai-api-card-actions">/)
    assert.match(source, /\.ai-api-card\s*{[\s\S]*grid-template-columns:\s*30px\s+minmax\(0,\s*1fr\)\s+auto;/)
    assert.match(source, /\.ai-api-card-actions\s*{[\s\S]*justify-self:\s*end;/)
    assert.doesNotMatch(source, /@click\.stop="testAiConnection\(provider\.id\)"/)
    assert.match(source, /@click\.stop="deleteAiProvider\(provider\.id\)"/)
    assert.doesNotMatch(source, /window\.confirm\(t\('settings\.aiDeleteProviderConfirm'/)
    assert.match(source, /import ModalDialog from '\.\/ModalDialog\.vue'/)
    assert.match(source, /:show="aiProviderDeleteDialog\.visible"/)
    assert.match(source, /@close="closeAiProviderDeleteDialog"/)
    assert.match(source, /@confirm="confirmAiProviderDelete"/)
    assert.match(source, /class="modal-btn primary" @click="confirmAiProviderDelete"/)
    assert.match(zhLocaleSource, /"aiDeleteProviderTitle":/)
    assert.match(enLocaleSource, /"aiDeleteProviderTitle":/)
    assert.match(zhLocaleSource, /"aiDeleteProviderConfirm":/)
    assert.match(enLocaleSource, /"aiDeleteProviderConfirm":/)
  })

  it('uses supplier wording and two icon actions for provider creation', () => {
    assert.doesNotMatch(source, /class="ui-select ai-preset-select"/)
    assert.doesNotMatch(source, /v-model="selectedAiProviderPresetId"/)
    assert.doesNotMatch(source, /t\('settings\.aiAddPresetProvider'\)/)
    assert.match(source, /class="ai-provider-icon-actions"/)
    assert.match(source, /class="ai-provider-icon-button ai-provider-icon-button--primary"/)
    assert.match(source, /class="ai-provider-icon-button"/)
    assert.match(source, /@click="addAiProvider"/)
    assert.match(source, /@click="toggleAiProviderPresetMenu"/)
    assert.match(source, /class="ai-provider-preset-menu"/)
    assert.match(source, /class="ai-provider-brand-mark"/)
    assert.doesNotMatch(source, /class="ai-provider-preset-mark"/)
    assert.match(source, /@click="addAiProviderFromPreset\(preset\.id\)"/)
    assert.match(zhLocaleSource, /"aiProviders":\s*"供应商"/)
    assert.doesNotMatch(zhLocaleSource, /模型服务商/)
  })

  it('lets the provider preset menu escape the supplier panel instead of being clipped', () => {
    assert.match(source, /\.ai-api-list-panel\s*{[\s\S]*overflow:\s*visible;/)
    assert.match(source, /\.ai-provider-create-menu\s*{[\s\S]*z-index:\s*20;/)
    assert.match(source, /\.ai-provider-preset-menu\s*{[\s\S]*z-index:\s*30;[\s\S]*left:\s*0;[\s\S]*width:\s*min\(236px,\s*calc\(100vw - 40px\)\);[\s\S]*max-height:\s*min\(520px,\s*calc\(100vh - 160px\)\);[\s\S]*overflow-y:\s*auto;/)
    assert.match(source, /\.ai-provider-preset-item\s*{[\s\S]*width:\s*100%;/)
  })

  it('closes the provider preset menu when clicking outside its create menu', () => {
    assert.match(source, /ref="aiProviderCreateMenuRef"/)
    assert.match(source, /const aiProviderCreateMenuRef = ref\(null\)/)
    assert.match(source, /function closeAiProviderPresetMenu\(\)\s*{\s*showAiProviderPresetMenu\.value = false\s*}/)
    assert.match(source, /function isAiProviderCreateMenuTarget\(target\)\s*{[\s\S]*const menuRefs = Array\.isArray\(aiProviderCreateMenuRef\.value\)[\s\S]*\? aiProviderCreateMenuRef\.value[\s\S]*: \[aiProviderCreateMenuRef\.value\][\s\S]*return menuRefs\.some\(menu => menu\?\.contains\?\.\(target\)\)[\s\S]*}/)
    assert.match(source, /function handleAiProviderPresetClickOutside\(event\)\s*{[\s\S]*if \(!showAiProviderPresetMenu\.value\) return[\s\S]*if \(isAiProviderCreateMenuTarget\(event\.target\)\) return[\s\S]*closeAiProviderPresetMenu\(\)[\s\S]*}/)
    assert.match(source, /document\.addEventListener\('click', handleAiProviderPresetClickOutside,\s*true\)/)
    assert.match(source, /document\.removeEventListener\('click', handleAiProviderPresetClickOutside,\s*true\)/)
  })

  it('keeps AI settings headers compact without redundant explanatory copy', () => {
    assert.doesNotMatch(source, /<strong>{{ t\('settings\.aiReplySettings'\) }}<\/strong>/)
    assert.doesNotMatch(source, /t\('settings\.aiProviderDetailHint'\)/)
  })

  it('groups AI general settings under one top-level section', () => {
    const commonSection = source.match(/<section class="ai-settings-section">\s*<h5 class="ai-settings-section-title">{{ t\('settings\.aiCommonSettings'\) }}<\/h5>[\s\S]*?<\/section>/)?.[0] ?? ''
    assert.match(source, /class="ai-settings-section-title">{{ t\('settings\.aiCommonSettings'\) }}<\/h5>/)
    assert.match(source, /class="ai-settings-card"/)
    assert.match(commonSection, /class="ai-settings-row-copy"[\s\S]*<strong>{{ t\('settings\.aiResponseLanguage'\) }}<\/strong>[\s\S]*t\('settings\.aiResponseLanguageDesc'\)/)
    assert.doesNotMatch(commonSection, /settings\.aiInlineCompletion/)
    assert.doesNotMatch(source, /class="ai-common-module"/)
    assert.doesNotMatch(source, /class="ai-common-panel"/)
    assert.doesNotMatch(source, /\.ai-common-body/)
    assert.match(source, /\.ai-settings-row\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+minmax\(220px,\s*360px\);/)
    assert.match(source, /\.ai-settings-row-copy span\s*{[\s\S]*color:\s*var\(--text-muted\);/)
    assert.match(source, /\.ai-switch input:checked \+ span\s*{[\s\S]*background:\s*var\(--accent-primary\);/)
    assert.match(zhLocaleSource, /"aiCommonSettings":\s*"通用设置"/)
    assert.match(enLocaleSource, /"aiCommonSettings":\s*"General Settings"/)
    assert.match(enLocaleSource, /"aiInlineCompletionDesc":\s*"Predict inline text and accept with Tab"/)
    assert.match(enLocaleSource, /"aiInlineCompletionEnabled":\s*"Enable inline suggestions"/)
  })

  it('groups inline completion settings under their own top-level section', () => {
    const inlineSection = source.match(/<section class="ai-settings-section">\s*<h5 class="ai-settings-section-title">{{ t\('settings\.aiInlineCompletion'\) }}<\/h5>[\s\S]*?<\/section>/)?.[0] ?? ''
    assert.match(inlineSection, /<strong>{{ t\('settings\.aiInlineCompletionEnabled'\) }}<\/strong>[\s\S]*t\('settings\.aiInlineCompletionDesc'\)[\s\S]*class="ai-switch"/)
    assert.match(inlineSection, /<strong>{{ t\('settings\.aiInlineCompletionDelay'\) }}<\/strong>[\s\S]*t\('settings\.aiInlineCompletionDelayDesc'\)/)
    assert.match(inlineSection, /<strong>{{ t\('settings\.aiInlineCompletionMaxChars'\) }}<\/strong>[\s\S]*t\('settings\.aiInlineCompletionMaxCharsDesc'\)/)
    assert.match(inlineSection, /<strong>{{ t\('settings\.aiInlineCompletionColor'\) }}<\/strong>[\s\S]*t\('settings\.aiInlineCompletionColorDesc'\)/)
    assert.match(inlineSection, /<strong>{{ t\('settings\.aiInlineCompletionOpacity'\) }}<\/strong>[\s\S]*t\('settings\.aiInlineCompletionOpacityDesc'\)/)
    assert.match(inlineSection, /<strong>{{ t\('settings\.aiInlineCompletionLogFiles'\) }}<\/strong>[\s\S]*t\('settings\.aiInlineCompletionLogFilesDesc'\)/)
    assert.match(zhLocaleSource, /"aiInlineCompletion":\s*"智能提示"/)
    assert.match(enLocaleSource, /"aiInlineCompletion":\s*"Inline AI Suggestions"/)
  })

  it('renders AI supplier details as one unified panel with equal section headers', () => {
    assert.match(source, /class="ai-settings-section-title">{{ t\('settings\.aiModelService'\) }}<\/h5>/)
    assert.match(source, /class="ai-provider-detail-shell"/)
    assert.match(source, /class="ai-provider-detail-section"/)
    assert.match(source, /class="ai-provider-detail-section-head"/)
    assert.match(source, /<strong>{{ t\('settings\.aiCurrentProviderDetail'\) }}<\/strong>[\s\S]*<strong>{{ t\('settings\.aiModels'\) }}<\/strong>/)
    assert.match(zhLocaleSource, /"aiModelService":\s*"模型服务"/)
    assert.match(zhLocaleSource, /"aiCurrentProviderDetail":\s*"供应商配置"/)
    assert.match(zhLocaleSource, /"aiModels":\s*"模型"/)
    assert.match(enLocaleSource, /"aiCurrentProviderDetail":\s*"Supplier Config"/)
    assert.doesNotMatch(source, /class="ai-provider-detail-area"/)
    assert.doesNotMatch(source, /class="ai-api-detail-panel"/)
    assert.match(source, /<header class="settings-toolbar" :class="\{ 'settings-toolbar--ai': !isSearching && activeSection === 'ai' \}">/)
    assert.match(source, /\.settings-toolbar--ai\s*{[\s\S]*width:\s*min\(1040px,\s*calc\(100% - 48px\)\);/)
    assert.match(source, /class="settings-groups" :class="\{ 'settings-groups--ai': !isSearching && activeSection === 'ai' \}"/)
    assert.match(source, /\.settings-groups--ai\s*{[\s\S]*width:\s*min\(1040px,\s*calc\(100% - 48px\)\);/)
    assert.match(source, /\.ai-config-layout\s*{[\s\S]*grid-template-columns:\s*minmax\(240px,\s*260px\)\s+minmax\(0,\s*1fr\);[\s\S]*border:\s*1px solid/)
    assert.match(source, /\.ai-provider-detail-shell\s*{[\s\S]*grid-template-columns:\s*minmax\(300px,\s*0\.95fr\)\s+minmax\(320px,\s*1\.05fr\);[\s\S]*border:\s*none;[\s\S]*box-shadow:\s*none;/)
    assert.match(source, /\.ai-provider-detail-section\s*{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;/)
    assert.match(source, /\.ai-provider-detail-section-head\s*{[\s\S]*min-height:\s*50px;[\s\S]*background:\s*transparent;/)
    assert.match(source, /\.ai-provider-detail-section\s*\+\s*\.ai-provider-detail-section\s*{[\s\S]*border-left:/)
    assert.match(source, /\.ai-model-list\s*{[\s\S]*align-content:\s*start;/)
    assert.match(source, /@media \(max-width:\s*1180px\)\s*{[\s\S]*\.ai-config-layout\s*{[\s\S]*grid-template-columns:\s*1fr;/)
    assert.match(source, /@media \(max-width:\s*980px\)\s*{[\s\S]*\.ai-provider-detail-shell\s*{[\s\S]*grid-template-columns:\s*1fr;/)
  })

  it('keeps AI provider defaults in the supplier config instead of binding them to the selected model', () => {
    assert.match(source, /:value="editingAiProvider\.temperature"/)
    assert.match(source, /@input="updateEditingAiProvider\(\{ temperature: \$event\.target\.value \}\); saveAiSettings\(\)"/)
    assert.match(source, /:value="editingAiProvider\.maxTokens"/)
    assert.match(source, /@input="updateEditingAiProvider\(\{ maxTokens: \$event\.target\.value \}\); saveAiSettings\(\)"/)
    assert.match(source, /:value="editingAiProvider\.timeoutMs"/)
    assert.match(source, /@input="updateEditingAiProvider\(\{ timeoutMs: \$event\.target\.value \}\); saveAiSettings\(\)"/)
    assert.doesNotMatch(source, /<template v-if="editingAiModel">/)
    assert.doesNotMatch(source, /updateEditingAiModel\(\{ temperature:/)
    assert.doesNotMatch(source, /updateEditingAiModel\(\{ maxTokens:/)
    assert.doesNotMatch(source, /updateEditingAiModel\(\{ timeoutMs:/)
    assert.match(source, /providers: settings\.providers\.map\(provider => \(\{[\s\S]*temperature: provider\.temperature,[\s\S]*maxTokens: provider\.maxTokens,[\s\S]*timeoutMs: provider\.timeoutMs,[\s\S]*models: provider\.models\.map/)
    assert.match(aiSettingsViewSource, /timeoutMs:\s*180000/)
    assert.match(aiSettingsSchemaSource, /timeoutMs:\s*180000/)
    assert.match(aiSettingsViewSource, /temperature: normalizeNumber\(safeProvider\.temperature/)
    assert.match(aiSettingsSchemaSource, /temperature: normalizeNumber\(provider\.temperature/)
  })

  it('keeps API keys masked in the input without stored-key helper badges', () => {
    assert.match(source, /const AI_MASKED_KEY_VALUE = '••••••••••••••••••••'/)
    assert.match(source, /:placeholder="editingAiProviderKey\?\.hasApiKey \? AI_MASKED_KEY_VALUE : t\('settings\.aiApiKeyPlaceholder'\)"/)
    assert.match(source, /@copy\.prevent/)
    assert.match(source, /@cut\.prevent/)
    assert.doesNotMatch(source, /t\('settings\.aiApiKeyConfigured'\)/)
    assert.doesNotMatch(source, /t\('settings\.aiApiKeyStored'\)/)
    assert.doesNotMatch(source, /t\('settings\.aiApiKeyMissing'\)/)
    assert.doesNotMatch(source, /<span class="ai-api-badge" :class="\{ 'ai-api-badge--warn': !editingAiProviderKey\?\.hasApiKey \}">/)
  })

  it('commits API key edits only on explicit field completion and can clear stored keys', () => {
    assert.match(source, /import \{ createAiApiKeyInputState \} from '\.\.\/utils\/aiApiKeyInputs'/)
    assert.match(source, /@input="setAiKeyInputValue\(editingAiProviderKey\?\.id, \$event\.target\.value\)"/)
    assert.match(source, /@blur="commitAiKeyInput\(editingAiProviderKey\?\.id\)"/)
    assert.match(source, /@keydown\.enter\.prevent="commitAiKeyInput\(editingAiProviderKey\?\.id\)"/)
    assert.doesNotMatch(source, /@input="setAiKeyInputValue\(editingAiProviderKey\?\.id, \$event\.target\.value\); saveAiSettings\(\)"/)
    assert.match(source, /const providerId = editingAiProvider\.value\?\.id \|\| ''[\s\S]*if \(!aiApiKeyInputState\.hasInput\(providerId, keyId\)\) return[\s\S]*await saveAiSettings\(\{ clearApiKeyInputs: true \}\)/)
    assert.match(source, /if \(aiApiKeyInputState\.hasInput\(provider\.id, key\.id\)\) \{[\s\S]*payloadKey\.apiKey = aiApiKeyInputState\.getProviderValue\(provider\.id, key\.id\)[\s\S]*\}/)
  })

  it('removes explicit AI save/test summary controls because edits autosave inline', () => {
    assert.doesNotMatch(source, /class="ai-detail-actions"/)
    assert.doesNotMatch(source, /@click="saveAiSettings\(\)">\s*{{ t\('settings\.save'\) }}/)
    assert.doesNotMatch(source, /<p v-if="aiTestMessage" class="settings-status"/)
  })

  it('lets users tune inline suggestion color in AI settings', () => {
    assert.match(source, /aiInlineCompletionColorOptions/)
    assert.match(source, /class="ai-inline-color-swatches"/)
    assert.match(source, /setInlineCompletionColorPreset\(option\.value\)/)
    assert.doesNotMatch(source, /updateInlineCompletionCustomColor/)
    assert.doesNotMatch(source, /ai-inline-color-picker/)
    assert.doesNotMatch(source, /{{ option\.label }}/)
    assert.match(source, /inlineCompletionOpacityPercent/)
    assert.match(source, /type="range" min="35" max="90" step="5"[\s\S]*@input="handleInlineCompletionOpacityInput"[\s\S]*@change="handleInlineCompletionOpacityChange"/)
    assert.match(source, /function updateLocalInlineCompletion\(patch = \{\}\)/)
    assert.match(zhLocaleSource, /"aiInlineCompletionColor":\s*"提示颜色"/)
    assert.match(enLocaleSource, /"aiInlineCompletionColor":\s*"Suggestion Color"/)
    assert.match(enLocaleSource, /"aiInlineCompletionColorRed":\s*"Red"/)
    assert.match(aiSettingsViewSource, /INLINE_COMPLETION_COLOR_PRESETS = \['gray', 'blue', 'cyan', 'green', 'red'\]/)
    assert.match(aiSettingsViewSource, /colorPreset:\s*'cyan'/)
    assert.match(aiSettingsSchemaSource, /colorPreset:\s*'cyan'/)
  })

  it('shows only the active settings section while browsing categories', () => {
    assert.match(source, /if \(!isSearching\.value\) \{[\s\S]*const section = currentSectionDefinition\.value[\s\S]*return section \? \[\{[\s\S]*rows: section\.rows\.filter\(row => matchesRow\(row\) && matchesShortcutCategory\(row, section\.id\)\)[\s\S]*\}\] : \[\][\s\S]*\}/)
    assert.match(source, /async function selectSection\(sectionId\) \{[\s\S]*activeSection\.value = sectionId[\s\S]*settingsContentRef\.value\?\.scrollTo\(\{ top: 0 \}\)/)
  })

  it('omits redundant inner section titles while browsing categories', () => {
    assert.match(source, /v-if="shouldShowSectionHeader\(section\)"/)
    assert.match(source, /<div v-if="shouldShowSectionTitle\(section\)" class="settings-group-head-copy">/)
    assert.match(source, /function shouldShowSectionTitle\(section\) \{[\s\S]*return Boolean\(section\) && isSearching\.value[\s\S]*\}/)
    assert.match(source, /function shouldShowSectionHeader\(section\) \{[\s\S]*return shouldShowSectionTitle\(section\) \|\| section\?\.id === 'shortcuts'[\s\S]*\}/)
  })

  it('uses an inline icon-only delete action for AI model rows', () => {
    assert.doesNotMatch(source, /t\('settings\.aiEditModel'\)/)
    assert.doesNotMatch(source, /class="ai-row-actions"/)
    assert.match(source, /class="ai-model-delete-button"/)
    assert.match(source, /:title="t\('settings\.aiDeleteApi'\)"/)
    assert.match(source, /:aria-label="`\$\{t\('settings\.aiDeleteApi'\)\} \$\{model\.name \|\| model\.model \|\| t\('settings\.aiModelId'\)\}`"/)
    assert.match(source, /@click="deleteAiModel\(model\.id\)"/)
    assert.match(source, /class="ai-model-inline-actions"/)
    assert.match(source, /\.ai-model-list-head,[\s\S]*\.ai-model-row\s*{[\s\S]*grid-template-columns:\s*minmax\(90px,\s*0\.95fr\)\s+minmax\(110px,\s*1fr\)\s+88px;/)
    assert.match(source, /\.ai-model-inline-actions\s*{[\s\S]*width:\s*88px;[\s\S]*gap:\s*1px;/)
    assert.match(source, /\.ai-model-status-icon\s*{[\s\S]*width:\s*24px;[\s\S]*height:\s*24px;/)
    assert.match(source, /\.ai-model-test-button,[\s\S]*\.ai-model-delete-button\s*{[\s\S]*width:\s*28px;[\s\S]*height:\s*28px;/)
  })

  it('tests AI connection from each model row using that model id', () => {
    assert.match(source, /v-if="aiTestingModelId === model\.id" class="ai-model-status-icon is-testing"/)
    assert.match(source, /:aria-label="t\('settings\.aiTesting'\)"/)
    assert.match(source, /\.ai-model-status-icon\.is-testing svg\s*{[\s\S]*animation:\s*ai-spin 1s linear infinite;/)
    assert.doesNotMatch(source, /\.ai-model-test-button\.is-testing svg\s*{[\s\S]*animation:\s*ai-spin 1s linear infinite;/)
    assert.match(source, /<span>{{ t\('settings\.aiConnectionStatus'\) }}<\/span>/)
    assert.match(source, /class="ai-model-test-button"/)
    assert.match(source, /:class="\{ 'is-testing': aiTestingModelId === model\.id \}"/)
    assert.match(source, /:disabled="aiTesting && aiTestingModelId !== model\.id"/)
    assert.match(source, /:title="aiTestingModelId === model\.id \? t\('settings\.aiTesting'\) : t\('settings\.aiTestConnection'\)"/)
    assert.match(source, /:aria-label="`\$\{t\('settings\.aiTestConnection'\)\} \$\{model\.name \|\| model\.model \|\| t\('settings\.aiModelId'\)\}`"/)
    assert.match(source, /@click="testAiConnection\(editingAiProvider\?\.id \|\| '', model\.id\)"/)
    assert.match(source, /async function testAiConnection\(providerId = '', modelId = ''\) \{[\s\S]*const targetModelId = modelId \|\| editingAiModel\.value\?\.id \|\| editingAiModelId\.value[\s\S]*window\.electronAPI\.testAIConnection\(\{ providerId: editingAiProvider\.value\?\.id \|\| '', modelId: editingAiModel\.value\?\.id \|\| '' \}\)/)
    assert.match(source, /aiModelTestResults\.value = \{[\s\S]*\[targetModelId\]: result\?\.ok \? 'success' : 'error'/)
    assert.match(source, /\.ai-model-list-head,[\s\S]*\.ai-model-row\s*{[\s\S]*grid-template-columns:\s*minmax\(90px,\s*0\.95fr\)\s+minmax\(110px,\s*1fr\)\s+88px;/)
  })

  it('keeps the existing settings content surfaces available', () => {
    assert.match(source, /v-model="searchQuery"/)
    assert.match(source, /resetAllShortcuts/)
    assert.match(source, /class="shortcut-simple-list"/)
    assert.match(source, /class="ai-settings-panel"/)
    assert.match(source, /handleOpenFileAssociations/)
    assert.match(source, /<AboutOverview \/>/)
  })
})
